version: '3.7'
services:
  app:
    build:
      context: .
      target: DJANGO_APP
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

