# Generated by Django 3.2.8 on 2021-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
